// Auto-generated by scripts/build_faq.py
// md5(FAQList) = 9d0f01783df0d525f15b2aca23f81d88

export const FAQList = [
  {
    question: "What is PollsApp?",
    answerParagraphs: [
      "PollsApp is an app for creating and participating in simple (but potentially important) polls.",
    ],
  },
  {
    question: "divider",
    answerParagraphs: [],
  },
  {
    question: "How do I vote in a poll?",
    answerParagraphs: [
      "By default, PollsApp opens with a [random poll](https://nuuuwan.github.io/polls_app/).",
      "You can also select from a list of public polls to vote in.",
    ],
  },
  {
    question: "How many times can I vote in a single poll?",
    answerParagraphs: [
      "You can vote any number of times. PollsApp will count your most recent vote.",
    ],
  },
  {
    question: "How do I create a poll?",
    answerParagraphs: [
      'Click on "Add New" in the Bottom Menu. Then, select your question, answer list, and whether the poll is public or unlisted. Finally, click "Add New Poll".',
    ],
  },
  {
    question:
      "What is the difference between a public poll and an unlisted poll?",
    answerParagraphs: [
      'Anyone can vote in a public poll. Public polls will be listed on the Polls page and could be chosen when you select "Random".',
      'Only people who have the Poll link (URL) can vote in unlisted polls. They are not listed on the Polls page and are not chosen when selecting "Random".',
    ],
  },
  {
    question: "How can I share a poll?",
    answerParagraphs: [
      "You can share a poll by copying its link. Anyone with the link can vote in that poll.",
      'You can also click the "Tweet" button to share a link to the poll on Twitter.',
    ],
  },
  {
    question: "divider",
    answerParagraphs: [],
  },
  {
    question: "Can I see the results of a poll?",
    answerParagraphs: [
      "When a poll has a minimum of 30 votes, PollsApp shows how many votes each answer received.",
    ],
  },
  {
    question:
      'Why does PollsApp say "Too close to call" when a particular answer has more votes?',
    answerParagraphs: [
      'PollsApp says, "Too close to call" when the difference between the top answer and the next answer is could be purely due to chance or random noise. Statisticians would say that "the difference is not [Statistically Significant](https://en.wikipedia.org/wiki/Statistical_significance)".',
      'Once the top answer is "significantly more" than the next, PollsApp will show "leads" instead of "Too close to call".',
    ],
  },
  {
    question: "What do the colours and line on the bar graph mean?",
    answerParagraphs: [
      "The line represents the percentage of votes the answer received. The darker shade represents a particular response's [95% confidence interval](https://en.wikipedia.org/wiki/Confidence_interval).",
    ],
  },
  {
    question: "divider",
    answerParagraphs: [],
  },
  {
    question: "Do I need to create a user account on the PollsApp?",
    answerParagraphs: [
      "For now, no. Polls All recognizes you by your IP Address, location and country and automatically creates a user account for you.",
      "You can see your automatic user account on the [User Page](https://nuuuwan.github.io/polls_app#user).",
    ],
  },
  {
    question: "How does PollsApp know that I have voted in a poll before?",
    answerParagraphs: [
      "PollsApp uses the above mentioned [automatic user account](https://nuuuwan.github.io/polls_app#user) to identify you.",
    ],
  },
  {
    question: "divider",
    answerParagraphs: [],
  },
  {
    question: "Where can I find the code for PollsApp?",
    answerParagraphs: [
      "You can find the code for PollsApp on [GitHub](https://github.com/nuuuwan/polls_app).",
      "Feel free to fork the code, report issues, or ask questions.",
    ],
  },
];
